name: List macOS Versions

on:
  workflow_dispatch:

jobs:
  list-versions:
    runs-on: macos-12.7.3
    steps:
      - name: List macOS Installers
        run: |
          softwareupdate --list-full-installers